Attribute VB_Name = "Module8"
Option Explicit
Sub make()
Analysis.cmbcatig.Clear
    Analysis.cmbcatig.AddItem "STEW/ TROSKINYS"
     Analysis.cmbcatig.AddItem "HOT DISHES/KARSTI PATIKELAI"
     Analysis.cmbcatig.AddItem "GARNISHES I GARNYRAI"
     Analysis.cmbcatig.AddItem "SIDES PUSÉS"
     Analysis.cmbcatig.AddItem "SNACKS I UZKANDZIAI"
     Analysis.cmbcatig.AddItem "DESERT / DESERTAI:"
     Analysis.cmbcatig.AddItem "NON - ALCOHOL DRINKS / NEALKOHOLINIAI GÉRIMAI:"


Analysis.cmbmeall.Clear
     Analysis.cmbmeall.AddItem "Pounded yam / jamso milty kose with Okro or(Okra)"
     Analysis.cmbmeall.AddItem "Pounded yam / jamso milty kose With Efo Riro"
     Analysis.cmbmeall.AddItem "Semolina / many kose with Ogbono"
     Analysis.cmbmeall.AddItem "Semolina / many kose with Okro or(Okra)"
     Analysis.cmbmeall.AddItem "Amala(yam flour)/jamo miltai With Egusi"
     Analysis.cmbmeall.AddItem "Fufu with Egusi"
     Analysis.cmbmeall.AddItem "Garri(eba) / fermentuota malta kasava With Efo Riro"
     Analysis.cmbmeall.AddItem "Semolina / many kose With Efo Riro"
     Analysis.cmbmeall.AddItem "White rice With Efo Riro"
     Analysis.cmbmeall.AddItem " Garri(eba) / fermentuota malta kasava With Egusi"
     Analysis.cmbmeall.AddItem "Pounded yam / jamso milty kose Egusi"
     Analysis.cmbmeall.AddItem "Semolina / many kose with Egusi"
     Analysis.cmbmeall.AddItem "Fried/fish(mackerel Fried stew)/ Keptazuvis (skumbre"
     Analysis.cmbmeall.AddItem "Goat meat Fried stew / OZkiena"
     Analysis.cmbmeall.AddItem "Beef Fried stew/ Jautiena"
     Analysis.cmbmeall.AddItem "Stew goat meat with white rice + dodo /Troskinta ozkiena su baltais ryziais,(ozkiena, planteinas,paprika, pomidorai, aliejus, svogúnai, kmynai, karis)"
     Analysis.cmbmeall.AddItem "Fufu with Ogbono"
     Analysis.cmbmeall.AddItem "Amala(yam flour)/Jamo miltai with Ogbono"
     Analysis.cmbmeall.AddItem "Pounded yam / jamso milty kose with Ogbono"
     Analysis.cmbmeall.AddItem "Amala(yam flour)/ jamo miltai With Efo Riro"
     Analysis.cmbmeall.AddItem "Amala(yam flour)/Jamo miltai with Okro or(Okra)"
     Analysis.cmbmeall.AddItem " Fufu with Okro or(Okra)"
     Analysis.cmbmeall.AddItem "Garri(eba) / fermentuota malta kasava with Ogbono"
    Analysis.cmbmeall.AddItem "Garri(eba) / fermentuota malta kasava with Okro or(Okra)"
    Analysis.cmbmeall.AddItem "Potato stew / (bulvés, morkos, svogünai, pomidorai, cesnakai,, paprika, aliejus, vistienos sultinys, pipirai, karis,vistiena)"
    Analysis.cmbmeall.AddItem "Potato porridge / Spinatai ,Darzoviy aliejus,, Raudonosios paprikos, pomidorai, svogúnas, imbiero cesnako, karis, skumbrê)"
    Analysis.cmbmeall.AddItem "BBQ chicken wings,(spicy / nospicy) (astrus/ neastrüs),(barbekiu vistienos sparneliai))"
    Analysis.cmbmeall.AddItem "Chicken Nuggets with french fries / Vistienos gabaléliai su bulvytèmis fri."
    Analysis.cmbmeall.AddItem "BBQ turkey wings (spicy / nospicy) (astrus/ neastrüs) / (barbekiu kalakutienos sparnelis)"
    Analysis.cmbmeall.AddItem "Fried rice with beef"
    Analysis.cmbmeall.AddItem "White Rice / Balti ryziai"
    Analysis.cmbmeall.AddItem "Spaghetti with veggies / Spagediai, (spicy / nospicy) (astrüs/ neastrüs), (spageciai, morkos, zirneliai, paprikos, svogünai, ¿esnakai, pipirai, palmiy aliejus)"
    Analysis.cmbmeall.AddItem "Spaghetti Jollof / Spageciai / (spicy / nospicy) (astrus/ neastrüs) / (spageciai, morkos, Zirneliai, paprikos, svogúnai, cesnakai, pipirai, palmiy aliejus) /"
   Analysis.cmbmeall.AddItem " Fried dodo with eggs/ Keptas dodo sukiausiniais"
    Analysis.cmbmeall.AddItem "Dodo / Kepti planteino griezinéliai (planteinas, aliejus, druska) (8 vnt)"
    Analysis.cmbmeall.AddItem "Beans Dodo with fried stew (baltosios pupeles, palmiy allejus, svogunal, vistienos sultinys, paprika, planteinas)"
    Analysis.cmbmeall.AddItem "Moin moin / Garintas pupeliu pyragas (pupeliu miltai, vistienos sultinys, paprika, svogünai, skumbre, kiausiniai, aliejus)"
    Analysis.cmbmeall.AddItem "Plantain chips / Planteiny traskuciai (jautiena, bulvés, morkos, svogüny laiskai, svogünai, kviediu 4,00 € miltai, aliejus, kmynai, jautienos sultinys, cesnakai)"
   Analysis.cmbmeall.AddItem " Meat pie / Mésos pyragas"
    Analysis.cmbmeall.AddItem "Puff Puff / saldzios spurgytes (8 vnt.)"
    Analysis.cmbmeall.AddItem "Onion rings / Svogüny Ziedai (8 vnt.)"
    Analysis.cmbmeall.AddItem "Ice cream with fruit / ledai su vaisiais"
    Analysis.cmbmeall.AddItem "Waffles"
    Analysis.cmbmeall.AddItem "Sprite (0,250 l)"
    Analysis.cmbmeall.AddItem "Fanta (0,250 l)"
    Analysis.cmbmeall.AddItem "Coca - cola / Coca - Cola zero (0,250 l)"
   Analysis.cmbmeall.AddItem " Cheesecake / sûrio pyragas"
   Analysis.cmbmeall.AddItem " Schweppes (0,250 l)"
    Analysis.cmbmeall.AddItem "Mineral water (carbonated, still) / Mineralinis vanduo (gazuotas, negazuotas) (0,330 l/0,750 l)"
    Analysis.cmbmeall.AddItem "Maltina Guinness"
    Analysis.cmbmeall.AddItem "Jollof rice with beef +dodo"
    Analysis.cmbmeall.AddItem "Jollof rice with beef"
    Analysis.cmbmeall.AddItem "Jollof Rice / Ryziai (spicy / nospicy) (astrüs/ neastrüs), (ryziai, vistienos sultinys, morkos, zirneliai, paprika, svogúnai,pomidorai)"
   Analysis.cmbmeall.AddItem " Indomie with Fried Eggs ('Indomie' makaronai su kiausiniu ir darzovémis (morkos, zirneliai, paprika, karis, aliejus)"
    Analysis.cmbmeall.AddItem "Fried rice with fish+dodo"
    Analysis.cmbmeall.AddItem "Fried Rice / Ryziai, (spicy / nospicy) (astrüs/ neastrüs) / (ryziai, ciberzole, zirneliai, morkos, paprika, jautiena, vistienos sultinys, svogunai)"
    Analysis.cmbmeall.AddItem "Fried Rice / Ryziai with Goat meat/ Ozkiena / (spicy / nospicy) (astrüs/ neastrüs) / (ryziai, ciberzole, zirneliai, morkos, paprika, jautiena, vistienos sultinys, svogünai)"
    Analysis.cmbmeall.AddItem "Fried Rice / Ryziai with Fried fish(mackerel) / Keptazuvis (spicy / nospicy) (astrüs/ neastrüs)/ (skumbrê)"
    Analysis.cmbmeall.AddItem "Fried fish with stew (mackerel) / Kepta zuvis (skumbre). (kepta zuvis marinuota zuvies prieskoniuose)"
    Analysis.cmbmeall.AddItem "Moin moin / Garintas pupeliy pyragas / (pupeliy miltai, vistienos sultinys, paprika, svogúnai, skumbre, kiausiniai, aliejus)"
    Analysis.cmbmeall.AddItem "Fried beef with stew / Kepta jautiena su troskiniu."
End Sub

    Sub display_analysis()
  
    Analysis.Show
     
End Sub
